FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY cmd/slowweb/ ./cmd/slowweb/

RUN CGO_ENABLED=0 GOOS=linux go build -o slowweb ./cmd/slowweb

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/slowweb .

CMD ["./slowweb"]
