FROM golang:1.25-alpine AS builder

WORKDIR /src

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /slowweb ./cmd/slowweb

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /slowweb .

CMD ["./slowweb"]
